export const COMPANY = {
  name: "FiberFastUSA",
  tagline: "Fiber Internet That Actually Works",
  phone: "(888) 555-FAST",
  phoneHref: "tel:+18885553278",
  email: "hello@fiberfastusa.com",
  hours: "Mon–Fri: 8am–8pm | Sat: 9am–5pm | Sun: Closed",
  address: "123 Fiber Lane, Denver, CO 80202",
  socialLinks: {
    facebook: "https://facebook.com/fiberfastusa",
    twitter: "https://x.com/fiberfastusa",
    instagram: "https://instagram.com/fiberfastusa",
    linkedin: "https://linkedin.com/company/fiberfastusa",
  },
} as const;

export type PlanTier = {
  readonly id: string;
  readonly name: string;
  readonly speed: string;
  readonly speedMbps: number;
  readonly price: number;
  readonly promoPrice: number | null;
  readonly giftCard: number;
  readonly freeMonths: number | null;
  readonly bestFor: string;
  readonly description: string;
  readonly isFeatured: boolean;
  readonly features: readonly string[];
};

export const PLANS: readonly PlanTier[] = [
  {
    id: "fast-500",
    name: "Fast 500",
    speed: "500 Mbps",
    speedMbps: 500,
    price: 34.99,
    promoPrice: null,
    giftCard: 50,
    freeMonths: 3,
    bestFor: "Streaming & browsing",
    description: "Great for streaming, browsing, and working from home.",
    isFeatured: false,
    features: [
      "500 Mbps download",
      "500 Mbps upload",
      "Stream 4K on 3+ devices",
      "Video calls & WFH ready",
      "Free installation",
      "Free router included",
      "$50 Visa Gift Card",
    ],
  },
  {
    id: "gig-1",
    name: "Gig 1",
    speed: "1 Gbps",
    speedMbps: 1000,
    price: 54.99,
    promoPrice: null,
    giftCard: 100,
    freeMonths: 3,
    bestFor: "Families & gaming",
    description: "Our most popular plan. Blazing fast speeds for the whole family.",
    isFeatured: true,
    features: [
      "1 Gbps download",
      "1 Gbps upload",
      "Stream 4K on 10+ devices",
      "Competitive gaming",
      "Large file downloads",
      "Smart home + security",
      "Free installation",
      "Free Wi-Fi 6E router",
      "$100 Visa Gift Card",
    ],
  },
  {
    id: "gig-2",
    name: "Gig 2",
    speed: "2 Gbps",
    speedMbps: 2000,
    price: 69.99,
    promoPrice: null,
    giftCard: 150,
    freeMonths: null,
    bestFor: "Power users",
    description: "Maximum performance for content creators, developers, and tech enthusiasts.",
    isFeatured: false,
    features: [
      "2 Gbps download",
      "2 Gbps upload",
      "Unlimited devices",
      "4K/8K streaming everywhere",
      "Zero lag gaming",
      "Content creation ready",
      "Free installation",
      "Free Wi-Fi 7 router",
      "$150 Visa Gift Card",
    ],
  },
  {
    id: "gig-5",
    name: "Gig 5",
    speed: "5 Gbps",
    speedMbps: 5000,
    price: 89.99,
    promoPrice: null,
    giftCard: 200,
    freeMonths: null,
    bestFor: "Ultra power users",
    description: "Insane speeds for homes that demand the absolute best.",
    isFeatured: false,
    features: [
      "5 Gbps download",
      "5 Gbps upload",
      "Unlimited devices",
      "8K streaming everywhere",
      "Pro-level gaming",
      "Content creation beast",
      "Free installation",
      "Free Wi-Fi 7 router",
      "Priority support",
      "$200 Visa Gift Card",
    ],
  },
  {
    id: "gig-7",
    name: "Gig 7",
    speed: "7 Gbps",
    speedMbps: 7000,
    price: 109.99,
    promoPrice: null,
    giftCard: 200,
    freeMonths: null,
    bestFor: "Extreme performance",
    description: "The fastest residential internet available. Period.",
    isFeatured: false,
    features: [
      "7 Gbps download",
      "7 Gbps upload",
      "Unlimited devices",
      "8K streaming everywhere",
      "Tournament-level gaming",
      "Professional content creation",
      "Free installation",
      "Free Wi-Fi 7 router",
      "Priority support",
      "Dedicated account manager",
      "$200 Visa Gift Card",
    ],
  },
] as const;

export type TeamMember = {
  readonly id: string;
  readonly slug: string;
  readonly name: string;
  readonly role: string;
  readonly bio: string;
  readonly phone: string;
  readonly email: string;
};

export const TEAM_MEMBERS: readonly TeamMember[] = [
  {
    id: "sarah-johnson",
    slug: "sarah-johnson",
    name: "Sarah Johnson",
    role: "Founder & CEO",
    bio: "Former cable executive turned fiber advocate. 15 years of telecom experience.",
    phone: "(888) 555-3278",
    email: "sarah@fiberfastusa.com",
  },
  {
    id: "mike-chen",
    slug: "mike-chen",
    name: "Mike Chen",
    role: "Head of Operations",
    bio: "Infrastructure expert dedicated to building the fastest fiber network nationwide.",
    phone: "(888) 555-3278",
    email: "mike@fiberfastusa.com",
  },
  {
    id: "james-rodriguez",
    slug: "james-rodriguez",
    name: "James Rodriguez",
    role: "Lead Technician",
    bio: "10+ years installing fiber. Every installation is handled with pride.",
    phone: "(888) 555-3278",
    email: "james@fiberfastusa.com",
  },
  {
    id: "emma-wilson",
    slug: "emma-wilson",
    name: "Emma Wilson",
    role: "Customer Success",
    bio: "24/7 support that actually answers the phone. Because you matter.",
    phone: "(888) 555-3278",
    email: "emma@fiberfastusa.com",
  },
] as const;

export const PLAN_INCLUDES = [
  "Free professional installation",
  "Free Wi-Fi router included",
  "24/7 local customer support",
  "No data caps — ever",
  "No contracts required",
  "30-day money-back guarantee",
] as const;

export const USE_CASES = [
  { id: "streaming", label: "Streaming (Netflix, YouTube, etc.)" },
  { id: "gaming", label: "Online Gaming" },
  { id: "wfh", label: "Work From Home" },
  { id: "smart-home", label: "Smart Home Devices" },
  { id: "family", label: "Family Use (5+ people)" },
  { id: "content", label: "Content Creation / Uploads" },
] as const;

export type Testimonial = {
  readonly id: string;
  readonly name: string;
  readonly city: string;
  readonly state: string;
  readonly quote: string;
  readonly rating: number;
  readonly isFeatured: boolean;
};

export const TESTIMONIALS: readonly Testimonial[] = [
  {
    id: "1",
    name: "Sarah M.",
    city: "Denver",
    state: "CO",
    quote: "Switched from cable and the difference is night and day. No more buffering, no more outages. My whole family streams at the same time without any issues.",
    rating: 5,
    isFeatured: true,
  },
  {
    id: "2",
    name: "James T.",
    city: "Dallas",
    state: "TX",
    quote: "I work from home and need reliable internet. FiberFastUSA has been rock solid — zero dropped Zoom calls in 6 months. Worth every penny.",
    rating: 5,
    isFeatured: true,
  },
  {
    id: "3",
    name: "Maria L.",
    city: "Phoenix",
    state: "AZ",
    quote: "The installation was quick and professional. The tech even helped me set up my smart home devices. Customer service is actually helpful here.",
    rating: 5,
    isFeatured: true,
  },
  {
    id: "4",
    name: "David K.",
    city: "Tampa",
    state: "FL",
    quote: "Finally, upload speeds that match download speeds. I'm a content creator and fiber has cut my upload times by 90%. Game changer.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "5",
    name: "Rachel P.",
    city: "Nashville",
    state: "TN",
    quote: "No contracts and no data caps? Sign me up. Been with FiberFastUSA for a year now and haven't had a single issue. Highly recommend.",
    rating: 4,
    isFeatured: false,
  },
  {
    id: "6",
    name: "Mike R.",
    city: "Atlanta",
    state: "GA",
    quote: "My kids game online while my wife and I stream 4K. No lag, no buffering. The Gig 1 plan handles everything we throw at it.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "7",
    name: "Priya S.",
    city: "Austin",
    state: "TX",
    quote: "We switched from AT&T and honestly can't believe the difference. Downloads that used to take 20 minutes now take seconds. The whole family is happy.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "8",
    name: "DeShawn W.",
    city: "Charlotte",
    state: "NC",
    quote: "As a streamer on Twitch, upload speed is everything. FiberFastUSA gives me symmetrical speeds that keep my stream crystal clear. No more dropped frames.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "9",
    name: "Jennifer H.",
    city: "Portland",
    state: "OR",
    quote: "Three kids doing homework online, my husband on Zoom, and me streaming Netflix — all at the same time with zero issues. This is what internet should be.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "10",
    name: "Carlos M.",
    city: "San Antonio",
    state: "TX",
    quote: "Muy contento con el servicio. The installer was professional and took the time to explain everything. Best internet service I've ever had in 15 years.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "11",
    name: "Aisha J.",
    city: "Memphis",
    state: "TN",
    quote: "I was skeptical about switching but the 30-day guarantee convinced me. Two months in and I wouldn't go back. The speed is incredible.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "12",
    name: "Brandon L.",
    city: "Raleigh",
    state: "NC",
    quote: "I run a small business from home and reliable internet is non-negotiable. FiberFastUSA has been flawless. Zero downtime in 8 months.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "13",
    name: "Kim N.",
    city: "Seattle",
    state: "WA",
    quote: "The customer service alone sets them apart. Called with a question at 10pm and got a real person who actually helped. That never happened with Comcast.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "14",
    name: "Jamal B.",
    city: "Houston",
    state: "TX",
    quote: "Gaming on fiber is a completely different experience. My ping went from 40ms to 3ms. I'm actually competitive now in ranked matches.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "15",
    name: "Lisa C.",
    city: "Minneapolis",
    state: "MN",
    quote: "No data caps is a game changer. We used to hit our cap every month with our old provider. Now we don't even think about it.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "16",
    name: "Wei Z.",
    city: "San Jose",
    state: "CA",
    quote: "As a software engineer working remotely, I push and pull large repos all day. The symmetric upload speeds have genuinely made me more productive.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "17",
    name: "Marcus T.",
    city: "Jacksonville",
    state: "FL",
    quote: "Installed in under 2 hours and the tech cleaned up after himself. Speed test showed even faster than what I'm paying for. Can't ask for more.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "18",
    name: "Fatima A.",
    city: "Detroit",
    state: "MI",
    quote: "My kids' online school has been seamless since we switched. Video calls don't freeze anymore and assignments upload instantly. Worth every cent.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "19",
    name: "Tyler O.",
    city: "Denver",
    state: "CO",
    quote: "Upgraded from the 500 Mbps to Gig 1 and the difference is noticeable. Multiple 4K streams plus gaming — this connection handles it all effortlessly.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "20",
    name: "Sofia R.",
    city: "Orlando",
    state: "FL",
    quote: "Finally an internet company that doesn't try to trick you with hidden fees. The bill is exactly what they quoted me. Refreshing honesty.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "21",
    name: "Andre D.",
    city: "Nashville",
    state: "TN",
    quote: "I produce music and upload stems to collaborators daily. What used to take an hour now takes minutes. Fiber has literally changed my workflow.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "22",
    name: "Hannah K.",
    city: "Salt Lake City",
    state: "UT",
    quote: "We have 15 smart home devices and they all work perfectly now. Our old internet couldn't handle it. Fiber handles everything without breaking a sweat.",
    rating: 4,
    isFeatured: false,
  },
  {
    id: "23",
    name: "Raj P.",
    city: "Phoenix",
    state: "AZ",
    quote: "Moved here from India and this is the best internet I've had anywhere in the world. Video calls to family back home are crystal clear every time.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "24",
    name: "Keisha M.",
    city: "Atlanta",
    state: "GA",
    quote: "The free installation was a huge plus. The technician was on time, professional, and even helped optimize my router placement for best coverage.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "25",
    name: "Chris F.",
    city: "Tampa",
    state: "FL",
    quote: "Retired and stream a lot of sports. The picture quality on fiber is noticeably better than what I had with cable. My wife loves it for her shows too.",
    rating: 4,
    isFeatured: false,
  },
  {
    id: "26",
    name: "Yuki T.",
    city: "Portland",
    state: "OR",
    quote: "I'm a photographer and regularly upload 50GB+ shoots to cloud storage. What used to be an overnight process now takes under an hour. Life changing.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "27",
    name: "Miguel V.",
    city: "Dallas",
    state: "TX",
    quote: "Toda mi familia está satisfecha. Five of us on different devices at the same time and the internet never slows down. Best service we've had.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "28",
    name: "Ashley W.",
    city: "Charlotte",
    state: "NC",
    quote: "I was paying more for slower cable internet. Switched to FiberFastUSA and got faster speeds for less money. Why didn't I do this sooner?",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "29",
    name: "Darnell J.",
    city: "Kansas City",
    state: "MO",
    quote: "The no-contract policy is what got me in the door. The incredible speed is what's keeping me. Fair pricing and honest service — rare combo these days.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "30",
    name: "Nina G.",
    city: "Scottsdale",
    state: "AZ",
    quote: "Our Ring cameras, Nest thermostats, and Alexa devices all run perfectly now. Our old provider couldn't handle the bandwidth. FiberFastUSA handles it easily.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "31",
    name: "Roberto S.",
    city: "San Diego",
    state: "CA",
    quote: "As someone who works in IT, I appreciate the technical quality. Low jitter, minimal packet loss, and consistent throughput. This is enterprise-grade residential internet.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "32",
    name: "Tasha B.",
    city: "Richmond",
    state: "VA",
    quote: "Single mom with three teenagers who are constantly online. FiberFastUSA keeps the peace at home because nobody has to fight over bandwidth anymore.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "33",
    name: "Kevin O.",
    city: "Omaha",
    state: "NE",
    quote: "Speed test consistently shows I'm getting even more than what I'm paying for. That never happened with my old provider. Genuinely impressed.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "34",
    name: "Mei L.",
    city: "Austin",
    state: "TX",
    quote: "My parents video call me from overseas every day. Since switching to fiber, the calls are smooth and clear. No more freezing or pixelated faces.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "35",
    name: "Jordan H.",
    city: "Boise",
    state: "ID",
    quote: "Just built a new house and FiberFastUSA was the obvious choice. Installation was included free and the speeds are exactly as advertised. No complaints.",
    rating: 4,
    isFeatured: false,
  },
  {
    id: "36",
    name: "Amara E.",
    city: "Columbus",
    state: "OH",
    quote: "I teach online classes and need zero interruptions. Haven't had a single connectivity issue since switching. My students notice the better video quality too.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "37",
    name: "Patrick M.",
    city: "Denver",
    state: "CO",
    quote: "The Gig 2 plan is overkill for most people but as a video editor, I need every bit of it. Downloading 4K raw footage is insanely fast now.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "38",
    name: "Lakshmi R.",
    city: "Nashville",
    state: "TN",
    quote: "We switched our entire extended family — six households — to FiberFastUSA. Everyone is thrilled. The referral bonuses were a nice touch too.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "39",
    name: "Trevor C.",
    city: "Tampa",
    state: "FL",
    quote: "I run a home-based e-commerce business and need rock-solid internet. FiberFastUSA has had 100% uptime for me. That directly impacts my bottom line.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "40",
    name: "Diana P.",
    city: "Las Vegas",
    state: "NV",
    quote: "Best decision we made this year. The whole switching process was painless — they even helped coordinate the timing so we had zero downtime between providers.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "41",
    name: "Kwame A.",
    city: "Houston",
    state: "TX",
    quote: "Came from Ghana two years ago and this is the fastest internet I've experienced. My whole family back home is jealous when we video chat.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "42",
    name: "Stephanie N.",
    city: "Raleigh",
    state: "NC",
    quote: "The 30-day money-back guarantee removed all the risk. Turned out I didn't need it — the service has been perfect from day one.",
    rating: 4,
    isFeatured: false,
  },
  {
    id: "43",
    name: "Hiroshi Y.",
    city: "Seattle",
    state: "WA",
    quote: "I play competitive Valorant and the low latency is a real advantage. My reaction times are the same but my shots actually register now. 3ms ping is no joke.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "44",
    name: "Monica G.",
    city: "San Antonio",
    state: "TX",
    quote: "We have a multigenerational household — grandparents streaming novelas, kids on YouTube, and us working. Never a single argument about slow internet anymore.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "45",
    name: "Isaiah W.",
    city: "Memphis",
    state: "TN",
    quote: "The tech who installed our fiber was incredibly knowledgeable. He ran the cable cleanly, tested everything, and even gave tips on network security. A+ service.",
    rating: 5,
    isFeatured: false,
  },
  {
    id: "46",
    name: "Elena V.",
    city: "Minneapolis",
    state: "MN",
    quote: "Moved from New York and was dreading finding a new ISP. FiberFastUSA made it easy. Faster and cheaper than what I had in Manhattan. Go figure.",
    rating: 5,
    isFeatured: false,
  },
] as const;

export const FAQ_ITEMS = [
  {
    question: "How fast is fiber internet?",
    answer: "FiberFastUSA offers plans from 500 Mbps up to 7 Gbps. Unlike cable, fiber delivers symmetric speeds — your upload speed matches your download speed. This means video calls, cloud backups, and file sharing are just as fast as streaming and browsing.",
  },
  {
    question: "Is fiber available at my address?",
    answer: "We're expanding rapidly across the United States. Use our Check Availability tool to see if your address is in our service area. If we're not there yet, sign up to be notified when we arrive in your area.",
  },
  {
    question: "Is there a contract or commitment?",
    answer: "No contracts, ever. All FiberFastUSA plans are month-to-month. You can cancel anytime with no early termination fees. We also offer a 30-day money-back guarantee.",
  },
  {
    question: "Are there data caps?",
    answer: "Absolutely not. All FiberFastUSA plans include unlimited data with no throttling, no caps, and no overage charges. Use as much internet as you want.",
  },
  {
    question: "How long does installation take?",
    answer: "Professional installation typically takes 2-4 hours. Our technicians handle everything from running the fiber line to setting up your Wi-Fi router. Most customers are online the same day.",
  },
  {
    question: "What equipment do I need?",
    answer: "Nothing — we provide everything. Every plan includes a free Wi-Fi router (Wi-Fi 6E or Wi-Fi 7 depending on your plan) and an Optical Network Terminal (ONT). There are no equipment rental fees.",
  },
  {
    question: "What's the difference between fiber and cable internet?",
    answer: "Fiber uses light signals through glass strands, while cable uses electrical signals through copper wires. Fiber is faster, more reliable, has lower latency, and isn't affected by distance or network congestion the way cable is. Check out our Why Fiber page for a detailed comparison.",
  },
  {
    question: "How do I cancel or change my plan?",
    answer: "Call us or email support. Plan changes take effect on your next billing cycle. Cancellations can be done anytime — no fees, no hassle.",
  },
  {
    question: "Do you offer business internet?",
    answer: "We currently focus on residential service. Business fiber plans are coming soon. Contact us if you're interested and we'll notify you when business plans launch.",
  },
  {
    question: "What areas do you serve?",
    answer: "We currently serve communities across the United States including Denver, Dallas, Phoenix, Tampa, Nashville, and more — with new areas being added every month. Check availability at your address to see if we're in your area.",
  },
] as const;

export const NAV_LINKS = [
  { href: "/pricing", label: "Pricing" },
  { href: "/why-fiber", label: "Why Fiber" },
  { href: "/about", label: "About" },
  { href: "/reviews", label: "Reviews" },
  { href: "/faq", label: "FAQ" },
  { href: "/contact", label: "Contact" },
] as const;

export const FOOTER_LINKS = {
  company: [
    { href: "/about", label: "About Us" },
    { href: "/reviews", label: "Reviews" },
    { href: "/contact", label: "Contact" },
    { href: "/careers", label: "Careers" },
    { href: "/verify-rep", label: "Verify a Rep" },
  ],
  services: [
    { href: "/pricing", label: "Plans & Pricing" },
    { href: "/check-availability", label: "Check Availability" },
    { href: "/get-started", label: "Get Started" },
    { href: "/why-fiber", label: "Why Fiber" },
  ],
  support: [
    { href: "/faq", label: "FAQ" },
    { href: "/contact", label: "Support" },
    { href: "/privacy", label: "Privacy Policy" },
    { href: "/terms", label: "Terms of Service" },
  ],
} as const;
