import locationsJson from "@/data/locations.json";
import { ISP_LABELS, type LeadIsp } from "@/lib/validations/lead-schema";

/**
 * City roll-up of the fiber footprint (map_pin, read-only), generated by
 * fiberfast-marketing/scripts/build_locations.py. Never hand-list cities here.
 */
export interface LocationProvider {
  id: string;
  homes: number;
  comingSoon: number;
  /** true = probe-verified live (Kinetic, Brightspeed); false = "available per records" (Frontier). */
  verified: boolean;
}

export interface Location {
  slug: string;
  city: string;
  state: string;
  stateSlug: string;
  stateName: string;
  verifiedLiveHomes: number;
  availablePerRecordsHomes: number;
  comingSoonHomes: number;
  providers: LocationProvider[];
  zips: string[];
  lat: number | null;
  lon: number | null;
}

export interface StateSummary {
  stateSlug: string;
  state: string;
  stateName: string;
  cities: Location[];
  homes: number;
}

export const LOCATIONS: readonly Location[] = locationsJson.locations;
export const LOCATIONS_GENERATED_AT = locationsJson.generatedAt;

export const NEARBY_LIMIT = 8;

export function totalHomes(location: Location): number {
  return location.verifiedLiveHomes + location.availablePerRecordsHomes;
}

export function listStates(): StateSummary[] {
  const byState = new Map<string, StateSummary>();
  for (const location of LOCATIONS) {
    const summary = byState.get(location.stateSlug) ?? {
      stateSlug: location.stateSlug, state: location.state, stateName: location.stateName, cities: [], homes: 0,
    };
    summary.cities.push(location);
    summary.homes += totalHomes(location);
    byState.set(location.stateSlug, summary);
  }
  return [...byState.values()].sort((a, b) => a.stateName.localeCompare(b.stateName));
}

export function findState(stateSlug: string): StateSummary | undefined {
  return listStates().find((summary) => summary.stateSlug === stateSlug);
}

export function findLocation(stateSlug: string, citySlug: string): Location | undefined {
  return LOCATIONS.find((location) => location.stateSlug === stateSlug && location.slug === citySlug);
}

/** Other cities in the same state, biggest footprint first. */
export function nearbyLocations(location: Location): Location[] {
  return LOCATIONS.filter((other) => other.stateSlug === location.stateSlug && other.slug !== location.slug)
    .sort((a, b) => totalHomes(b) - totalHomes(a))
    .slice(0, NEARBY_LIMIT);
}

export function locationPath(location: Pick<Location, "stateSlug" | "slug">): string {
  return `/fiber/${location.stateSlug}/${location.slug}`;
}

export function providerName(id: string): string {
  return id in ISP_LABELS ? ISP_LABELS[id as LeadIsp] : id;
}

export function formatHomes(count: number): string {
  return count.toLocaleString("en-US");
}
