-- public_leads v2 — durable buffer for every inbound lead (web, canvasser, Meta form).
-- Owner rule (2026-09-11): leads never expire and are never deleted; every consent + status change is kept.

ALTER TABLE public_leads
  ALTER COLUMN email DROP NOT NULL,
  ALTER COLUMN service_address SET NOT NULL,
  ADD COLUMN IF NOT EXISTS lead_number BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) UNIQUE,
  -- where the home is
  ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS lon DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS address_accuracy TEXT,
  ADD COLUMN IF NOT EXISTS address_hash TEXT,            -- scraper home_hash; same value as map_pin / pins
  -- what we knew at submit time (snapshot, never recomputed)
  ADD COLUMN IF NOT EXISTS isp_declared TEXT,            -- canvasser's pick
  ADD COLUMN IF NOT EXISTS current_provider TEXT,        -- homeowner's current ISP (mirrors the winning Meta form)
  ADD COLUMN IF NOT EXISTS serviceability_status TEXT CHECK (serviceability_status IN ('live', 'coming_soon', 'not_serviceable', 'unknown')),
  ADD COLUMN IF NOT EXISTS serviceability JSONB,
  -- channel + attribution
  ADD COLUMN IF NOT EXISTS lead_channel TEXT NOT NULL DEFAULT 'web' CHECK (lead_channel IN ('web', 'rep', 'meta_form')),
  ADD COLUMN IF NOT EXISTS rep_slug TEXT,
  ADD COLUMN IF NOT EXISTS utm_content TEXT,
  ADD COLUMN IF NOT EXISTS utm_term TEXT,
  ADD COLUMN IF NOT EXISTS fbclid TEXT,
  ADD COLUMN IF NOT EXISTS gclid TEXT,
  ADD COLUMN IF NOT EXISTS fbc TEXT,
  ADD COLUMN IF NOT EXISTS fbp TEXT,
  ADD COLUMN IF NOT EXISTS landing_path TEXT,
  ADD COLUMN IF NOT EXISTS referrer TEXT,
  -- TCPA express written consent (audit evidence)
  ADD COLUMN IF NOT EXISTS consent_contact BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS consent_text_version TEXT,
  ADD COLUMN IF NOT EXISTS consent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS consent_ip TEXT,
  ADD COLUMN IF NOT EXISTS consent_user_agent TEXT,
  -- downstream delivery
  ADD COLUMN IF NOT EXISTS crm_sync_status TEXT NOT NULL DEFAULT 'pending' CHECK (crm_sync_status IN ('pending', 'synced', 'failed')),
  ADD COLUMN IF NOT EXISTS crm_sync_attempts INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS crm_sync_error TEXT,
  ADD COLUMN IF NOT EXISTS crm_synced_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS crm_pin_id TEXT,
  ADD COLUMN IF NOT EXISTS notified_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS capi_event_id TEXT;

CREATE INDEX IF NOT EXISTS idx_leads_crm_pending ON public_leads (created_at) WHERE crm_sync_status <> 'synced';
CREATE INDEX IF NOT EXISTS idx_leads_phone ON public_leads (phone);
CREATE INDEX IF NOT EXISTS idx_leads_address_hash ON public_leads (address_hash);

-- Append-only audit trail: one row per thing that happened to a lead.
CREATE TABLE IF NOT EXISTS public_lead_events (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  lead_id UUID NOT NULL REFERENCES public_leads (id),
  event_type TEXT NOT NULL,        -- submitted | consent_captured | crm_synced | crm_sync_failed | notified | capi_sent | status_changed
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_lead_events_lead ON public_lead_events (lead_id, created_at);
ALTER TABLE public_lead_events ENABLE ROW LEVEL SECURITY;   -- no anon policies: server (service role) only

-- Status changes are recorded automatically so nothing depends on app code remembering to log.
CREATE OR REPLACE FUNCTION log_public_lead_status_change() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status OR NEW.crm_sync_status IS DISTINCT FROM OLD.crm_sync_status THEN
    INSERT INTO public_lead_events (lead_id, event_type, payload)
    VALUES (NEW.id, 'status_changed', jsonb_build_object(
      'status', jsonb_build_array(OLD.status, NEW.status),
      'crm_sync_status', jsonb_build_array(OLD.crm_sync_status, NEW.crm_sync_status)));
  END IF;
  NEW.updated_at := NOW();
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_public_leads_status_change ON public_leads;
CREATE TRIGGER trg_public_leads_status_change BEFORE UPDATE ON public_leads
  FOR EACH ROW EXECUTE FUNCTION log_public_lead_status_change();

-- Leads are evidence. Refuse deletes at the database, whoever asks.
CREATE OR REPLACE FUNCTION refuse_public_lead_delete() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'public_leads rows are never deleted (audit trail). Mark status=closed instead.';
END $$;
DROP TRIGGER IF EXISTS trg_public_leads_no_delete ON public_leads;
CREATE TRIGGER trg_public_leads_no_delete BEFORE DELETE ON public_leads
  FOR EACH ROW EXECUTE FUNCTION refuse_public_lead_delete();
DROP TRIGGER IF EXISTS trg_public_lead_events_no_delete ON public_lead_events;
CREATE TRIGGER trg_public_lead_events_no_delete BEFORE DELETE ON public_lead_events
  FOR EACH ROW EXECUTE FUNCTION refuse_public_lead_delete();

-- The anon insert policy from 00001 is no longer needed: submissions go through the server action (service role).
DROP POLICY IF EXISTS "Anyone can submit a lead" ON public_leads;
